---
name: Lint

on:
  pull_request:
  push:
    branches: [develop]
  workflow_dispatch:

permissions:
  contents: read
  statuses: write
  pull-requests: write

jobs:
  lint:
    uses: LukeEvansTech/shared-workflows/.github/workflows/super-linter.yml@b2f62f289700dca10b92707872be16bf379cf8c1 # v1
    with:
      default-branch: develop
      soft-launch: false
      filter-regex-exclude: '(^|/)(vendor|node_modules|\.terraform|\.venv|dist|build)/|.*\.tmpl$'
